### PR TITLE
Updating the guide for setting up the project in local

### PR DESCRIPTION
**Pull request by Barabasbalazs**
I am fairly new to this project.
When I tried setting it up on my local machine, the migration scripts wouldn't run properly in the app/builder folder. I updated the docs with what worked for me.

### CODE REVIEW

**Comment by istarkov** [comment]
We have the following devcontainer install script, and as you can see, the code there differs from your suggestions.

https://github.com/webstudio-is/webstudio/blob/d3d19e77fd1bf2925849a8ea898a68b5e6026117/.devcontainer/postinstall.sh#L25-L27

A devcontainer is like a newly created, empty Linux environment, and it doesn’t have issues with migrations or environment setup.

It looks the issue is:
instead of:
`Go to the project root directory and run the following command to create the database schema:`

you did:
> the migration scripts wouldn't run properly in the app/builder folder

**Comment by istarkov** [comment]
Seems like the issue that running from the root folder you got on

```
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "migrations" not found
 ELIFECYCLE  Command failed with exit code 254.
```

It's a bug. We need to fix it in the main repo. Thank you

**Comment by istarkov** [comment]
fixed here
https://github.com/webstudio-is/webstudio/pull/4241

**Comment by Barabasbalazs** [comment]
I figured something was off with the scripts. Thanks for fixing it. No need to update the docs then

**Pull request closed without merging**
